In [107]:
import numpy as np

# Linear Algebra Tasks

## 1. Matrix Creation and Manipulation

### Create various types of matrices (zero matrix, identity matrix, random matrix).

In [108]:
zero_matrix = np.zeros((3, 3))

identity_matrix = np.eye(3)

random_matrix = np.random.rand(3, 3)

In [109]:
print(zero_matrix, '\n')
print(identity_matrix, '\n')
print(random_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0.8135294  0.6171321  0.11935668]
 [0.01272232 0.55052738 0.48300081]
 [0.43364224 0.5035375  0.14724361]]


### Perform basic matrix operations (addition, subtraction, multiplication).

In [110]:
matrix_sum = zero_matrix + identity_matrix

matrix_diff = identity_matrix - zero_matrix

matrix_product = random_matrix * 2

matrix_div = identity_matrix / 2

In [111]:
matrix_sum, matrix_diff, matrix_product, matrix_div

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1.6270588 , 1.23426421, 0.23871336],
        [0.02544464, 1.10105476, 0.96600162],
        [0.86728447, 1.00707499, 0.29448722]]),
 array([[0.5, 0. , 0. ],
        [0. , 0.5, 0. ],
        [0. , 0. , 0.5]]))

### Transpose a matrix and find the determinant and inverse of a matrix.

In [112]:
transposed_matrix = np.transpose(random_matrix)

determinant = np.linalg.det(random_matrix)

inverse_matrix = np.linalg.inv(random_matrix)

In [113]:
print("Transpose")
print(transposed_matrix)

print("\nDeterminant")
print(determinant)

print("\nInverse")
print(inverse_matrix)

Transpose
[[0.8135294  0.01272232 0.43364224]
 [0.6171321  0.55052738 0.5035375 ]
 [0.11935668 0.48300081 0.14724361]]

Determinant
-0.03153931092976692

Inverse
[[  5.14111996   0.97555063  -7.36750998]
 [ -6.58150942  -2.15695604  12.41044447]
 [  7.36622813   4.50320586 -13.95144168]]


## 2. Solving Linear Equations

### Use NumPy to solve a system of linear equations.

In [114]:
A = np.array([[3, 1], [1, 2]])

b = np.array([9, 8])

solution = np.linalg.solve(A, b)
solution

array([2., 3.])

### Implement matrix factorization methods (LU decomposition, QR decomposition).

In [115]:
# LU decomposition
from scipy.linalg import lu

P, L, U = lu(A)

(P, L, U), A

((array([[1., 0.],
         [0., 1.]]),
  array([[1.        , 0.        ],
         [0.33333333, 1.        ]]),
  array([[3.        , 1.        ],
         [0.        , 1.66666667]])),
 array([[3, 1],
        [1, 2]]))

In [116]:
# QR decomposition
Q, R = np.linalg.qr(A)

(P, L, U), (Q, R)

((array([[1., 0.],
         [0., 1.]]),
  array([[1.        , 0.        ],
         [0.33333333, 1.        ]]),
  array([[3.        , 1.        ],
         [0.        , 1.66666667]])),
 (array([[-0.9486833 , -0.31622777],
         [-0.31622777,  0.9486833 ]]),
  array([[-3.16227766, -1.58113883],
         [ 0.        ,  1.58113883]])))

## 3. Eigenvalues and Eigenvectors

### Calculate the eigenvalues and eigenvectors of a given matrix.

In [117]:
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvalues, eigenvectors

(array([3.61803399, 1.38196601]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

### Verify the results by reconstructing the original matrix.

In [118]:
reconstructed_matrix = np.dot(eigenvectors, np.dot(np.diag(eigenvalues), np.linalg.inv(eigenvectors)))

np.allclose(A, reconstructed_matrix)

True

In [119]:
A, reconstructed_matrix

(array([[3, 1],
        [1, 2]]),
 array([[3., 1.],
        [1., 2.]]))

## 4. Vector Operations

### Perform basic vector operations (addition, dot product, cross product).

In [120]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [121]:
vector_sum = np.add(v1, v2)

dot_product = np.dot(v1, v2)

cross_product = np.cross(v1, v2)

In [122]:
vector_sum, dot_product, cross_product

(array([5, 7, 9]), 32, array([-3,  6, -3]))

### Normalize a vector and compute vector norms.

In [123]:
norm_v1 = v1 / np.linalg.norm(v1)

norm = np.linalg.norm(v1)

In [124]:
norm_v1, norm

(array([0.26726124, 0.53452248, 0.80178373]), 3.7416573867739413)

## 5. Matrix Decomposition

### Understand and implement Principal Component Analysis (PCA) using SVD.

In [125]:
data_matrix = np.random.rand(5, 5)

U, S, Vt = np.linalg.svd(data_matrix)

principal_components = np.dot(U, np.diag(S))

principal_components

array([[-1.49748695,  0.23275411, -0.11906979, -0.13247888, -0.00289193],
       [-0.78749378, -0.38070668,  0.20683982, -0.04283401,  0.01183981],
       [-1.23110601, -0.64395054, -0.08264527,  0.06424947, -0.00664941],
       [-0.66662165,  0.22242383, -0.26787631,  0.07759759,  0.01001603],
       [-1.24965774,  0.47673593,  0.2366549 ,  0.08105481, -0.0027879 ]])

# Calculus Tasks

## 1. Numerical Differentiation

### Implement forward, backward, and central difference methods for differentiation.

In [126]:
def f(x):
    return x**2 + 2*x + 1

def forward_difference(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

def backward_difference(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

def central_difference(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

In [127]:
x_point = 10.0
forward_diff = forward_difference(f, x_point)
backward_diff = backward_difference(f, x_point)
central_diff = central_difference(f, x_point)

In [128]:
forward_diff, backward_diff, central_diff

(22.000010000056132, 21.999989999699206, 21.99999999987767)

## 2. Numerical Integration

### Use NumPy to compute the numerical integral of a given function.

In [129]:
def f(x):
    return x**2 + 2*x + 1

### Implement the trapezoidal rule and Simpson's rule for integration.

In [130]:
def trapezoidal_rule(f, a, b, n=100):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral

# Define the interval
a = 2
b = 5

In [131]:
trapezoidal_integral = trapezoidal_rule(f, a, b)
round(trapezoidal_integral, 2)

63.0

In [132]:
def simpsons_rule(f, a, b, n=100):
    if n % 2 == 1:
        n += 1  # n must be even
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 3) * (y[0] + 4 * np.sum(y[1:n:2]) + 2 * np.sum(y[2:n-1:2]) + y[-1])
    return integral

In [133]:
simpsons_integral = simpsons_rule(f, a, b)
round(simpsons_integral, 2)

63.0

## 3. Partial Derivatives

### Calculate partial derivatives of multivariable functions using NumPy.

In [134]:
def f(x, y):
    return x**2 + y**2

def partial_derivative_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x, y)) / h

def partial_derivative_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y)) / h

x_point = 1.0
y_point = 2.0

In [135]:
partial_x = partial_derivative_x(f, x_point, y_point)
partial_y = partial_derivative_y(f, x_point, y_point)

partial_x, partial_y

(2.00001000001393, 4.000010000027032)

### Verify results by comparing with analytical solutions.

In [136]:
analytical_partial_x = 2 * x_point
analytical_partial_y = 2 * y_point

comparison_x = np.isclose(partial_x, analytical_partial_x)
comparison_y = np.isclose(partial_y, analytical_partial_y)

partial_x, partial_y, analytical_partial_x, analytical_partial_y, comparison_x, comparison_y

(2.00001000001393, 4.000010000027032, 2.0, 4.0, True, True)

In [137]:
print(f"Numerical partial derivative with respect to x: {partial_x}")
print(f"Analytical partial derivative with respect to x: {analytical_partial_x}")
print(f"Comparison (x): {comparison_x}")

print(f"Numerical partial derivative with respect to y: {partial_y}")
print(f"Analytical partial derivative with respect to y: {analytical_partial_y}")
print(f"Comparison (y): {comparison_y}")


Numerical partial derivative with respect to x: 2.00001000001393
Analytical partial derivative with respect to x: 2.0
Comparison (x): True
Numerical partial derivative with respect to y: 4.000010000027032
Analytical partial derivative with respect to y: 4.0
Comparison (y): True


## 4. Optimization

### Use NumPy to solve optimization problems with constraints.

In [138]:
from scipy.optimize import minimize

In [139]:
def objective_function(x):
    return (x[0] - 1)**2 + (x[1] - 2.5)**2

def constraint1(x):
    return 3 - (x[0] + 2 * x[1])  # x + 2y <= 3

def constraint2(x):
    return x[0]  # x >= 0

def constraint3(x):
    return x[1]  # y >= 0

In [140]:
x0 = np.array([0.5, 0.5])

cons = [{'type': 'ineq', 'fun': constraint1},
        {'type': 'ineq', 'fun': constraint2},
        {'type': 'ineq', 'fun': constraint3}]

solution = minimize(objective_function, x0, method='SLSQP', constraints=cons)

In [141]:
print('Optimal value:', solution.fun)
print('Optimal variables:', solution.x)

Optimal value: 1.799999999999998
Optimal variables: [0.4 1.3]
