In [1]:
import numpy as np

# Indexing and Slicing

### 1. Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

In [9]:
array_2d = np.array([[1, 2, 3, 4, 5, 6],
                   [7, 8, 9, 10, 11, 12],
                   [13, 14, 15, 16, 17, 18],
                   [19, 20, 21, 22, 23, 24],
                   [25, 26, 27, 28, 29, 30],
                   [31, 32, 33, 34, 35, 36]])

print(array_2d)

sub_array_2d = array_2d[1:3, 1:3]

print(sub_array_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 8  9]
 [14 15]]


### 2. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [13]:
array_3d = np.arange(6).reshape(3, 2, 1)

print(array_3d)

sub_array_3d = array_3d[0:2, :, 0]

print(sub_array_3d)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
[[0 1]
 [2 3]]


### 3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [18]:
array_int = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

fancy_indexed = array_int[[1, 3, 4, 6]]

print(fancy_indexed)

[1 3 4 6]


### 4. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [40]:
array_2d_fancy = np.arange(25).reshape(5, 5)

print(array_2d_fancy)

rows = np.array([0, 2, 2])
cols = np.array([1, 3])

fancy_selected = array_2d_fancy[rows[:, np.newaxis], cols]

print(fancy_selected)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  3]
 [11 13]
 [11 13]]



### 5. From a 1D array of random integers, extract all elements that are greater than 8.


In [47]:
array_random = np.random.randint(0, 15, size=10)

print('Original Array: ', array_random)

greater_than_8 = array_random[array_random > 8]

print('Output: ', greater_than_8)


Original Array:  [ 9  3 12 14 11 13  7  6  8  9]
Output:  [ 9 12 14 11 13  9]


### 6. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.


In [51]:
array_2d_replace = np.arange(36).reshape(6,6)

print(array_2d_replace)

array_2d_replace[array_2d_replace > 13] = 0

print(array_2d_replace)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


# Broadcasting

### 1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [55]:
array_1d_broadcast = np.array([1, 2, 3])
print(array_1d_broadcast)

array_2d_broadcast = np.arange(12).reshape(4,3)
print(array_2d_broadcast)

result = array_2d_broadcast + array_1d_broadcast

print('\n',result)


[1 2 3]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


### 2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).


In [57]:
array_2d_mult = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d_mult)

array_1d_mult = np.array([1, 2, 3])
print(array_1d_mult)

result_mult = array_2d_mult * array_1d_mult

print('\n',result_mult)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]

 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### 3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.


In [63]:
array_2d_1 = np.array([[1], [2], [3]])
array_2d_2 = np.array([[1, 2, 3, 4]])

print(array_2d_1.shape, array_2d_2.shape, '\n')

result_add = array_2d_1 + array_2d_2

print(result_add)


(3, 1) (1, 4) 

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


### 4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.


In [71]:
array_3d_add = np.arange(12).reshape(3,4)
print(array_3d_add)

array_2d_add = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array_2d_add)

result_add_3d = array_3d_add + array_2d_add

print('\n',result_add_3d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


# Some more

### 1. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [77]:
array_2d_some = np.arange(36).reshape(6, 6)
print(array_2d_some)

sliced_array = array_2d_some[1:6:2, 1:6:2]
print(sliced_array)

array_1d_some = np.array([1, 2, 3])

result_some = sliced_array + array_1d_some

print('\n',result_some)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 7  9 11]
 [19 21 23]
 [31 33 35]]

 [[ 8 11 14]
 [20 23 26]
 [32 35 38]]


### 2. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [82]:
array_3d_some = np.arange(6).reshape(3, 2, 1)
print(array_3d_some)

sub_array_some = array_3d_some[:, :, 0]
print('\n',sub_array_some)

array_2d_subtract = np.array([[1, 2], [3, 4], [5, 6]])
print('\n',array_2d_subtract)

result_subtract = sub_array_some - array_2d_subtract

print('\n',result_subtract)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

 [[0 1]
 [2 3]
 [4 5]]

 [[1 2]
 [3 4]
 [5 6]]

 [[-1 -1]
 [-1 -1]
 [-1 -1]]


### 3. Given a 2D array, extract the diagonal elements and create a 1D array.


In [83]:
array_2d_diag = np.arange(16).reshape(4, 4)
print(array_2d_diag)

diagonal_elements = np.diag(array_2d_diag)

print(diagonal_elements)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]


### 4. Use slicing to reverse the order of elements in each row of a 2D array.


In [85]:
array_2d_reverse = np.arange(16).reshape(4, 4)
print(array_2d_reverse)

reversed_array = array_2d_reverse[:, ::-1]

print('\n',reversed_array)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


### 5. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.


In [88]:
array_3d_large = np.random.randint(0, 20, size=(7, 6, 5)) 

sub_array_large = array_3d_large[:2, :3, :4]

array_1d_large = np.array([1, 2, 3, 4])

result_large = sub_array_large + array_1d_large

print(result_large)


[[[ 8 14 11  6]
  [ 5 11 12  4]
  [ 5  4  9 10]]

 [[ 4 20 20 13]
  [11 17 12  9]
  [14 18 12  4]]]


### 6. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.


In [92]:
array_2d_final = np.arange(25).reshape(5, 5)
print(array_2d_final)

array_2d_final[:, -1] = array_2d_final[:, 0] + array_2d_final[:, 1]

print('\n', array_2d_final)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 [[ 0  1  2  3  1]
 [ 5  6  7  8 11]
 [10 11 12 13 21]
 [15 16 17 18 31]
 [20 21 22 23 41]]
